name: Deploy Chamados

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USER_NAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USER_NAME }}/chamados .

      - name: push image docker
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/chamados

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Debug imagem Docker
        run: echo "${{ secrets.DOCKER_USER_NAME }}/chamados"
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USER_NAME }}/chamados:latest
      - name: Remove docker container
        run: docker rm -f chamados_api
      - name: Run docker container
        run: sudo docker run -d --name chamados_api -p 8080:8080 -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e JWT_SECRET=${{secrets.JWT_SECRET}} --network net-api cesar468dev/chamados